### ISSUE TITLE
Better user management

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/secret#1]
It would be nice to specify users (email addresses) as arguments to arguments, instead of private keys...

**Comment by gaborcsardi** [comment]
For example, have a config file that specifies an email address -> private key mapping. Or sg like that.

But if we assume that a user usually uses a single key-pair, then this is not terribly important, we should just allow setting the key(s) via R options and also environment variables, and we are good.

**Comment by andrie** [comment]
I think this has already been implemented?
