### ISSUE TITLE
Expose an easy way to view secrets and who it's shared with

### ISSUE THREAD

**Issue by andrie** [gaborcsardi/secret#11]
Perhaps extend `share_secret()` to report who the secret is shared with, when `email=NULL`

**Comment by gaborcsardi** [comment]
:+1:

**Comment by gaborcsardi** [comment]
On a second thought, I will change this API a bit and add a separate function for listing secrets and who has access to them.

**Comment by gaborcsardi** [comment]
Done in f0733b999c04d420116333eb76263fad0116db4e

`list_secrets()$email` is a list column now.
