### ISSUE TITLE
How do we deal with orphaned secrets when deleting a user?

### ISSUE THREAD

**Issue by andrie** [gaborcsardi/secret#12]
Imagine a secret `foo` is shared with `alice`, and only with `alice`.

If you delete `alice`, this will leave an orphaned secret `foo` in the system.

There is no way to interact with this secret, because the key file no longer exists.

How should we deal with this?

Options:

1. Throw a warning when leaving orphaned secrets behind?
2. Throw a warning and don't delete the secret?
3. Delete the user *and* delete the secret?

In either case, we should:

* Expose a function to identify orphaned secrets

**Comment by andrie** [comment]
@gaborcsardi Do you have any preferred option?

I think the least confusing option is 1.:

* Throw a warning when leaving orphaned secrets behind?
* Expose a function to identify orphaned secrets

**Comment by gaborcsardi** [comment]
WArning is done. Identifying the orphaned secrets is also easy with `list_secrets()`.
