### ISSUE TITLE
Match private key to user with fingerprint

### ISSUE THREAD

**Issue by jiwalker-usgs** [gaborcsardi/secret#18]
Not sure if you have a suggestion label, but instead of looping over the users .enc files until one works, the user "name" or email could be matched by checking the fingerprints of the key and the users public key fingerprints.  Something like:

```r
for (pubkey in dir('vault/users/' pattern='.pem$')) {
  pubkeyfile = file.path('inst', 'vault', 'users', pubkey)
  if (as.character(fingerprint(key)) == as.character(fingerprint(read_pubkey(pubkeyfile)))) {
    return(pubkey)
  }
}
```

**Comment by gaborcsardi** [comment]
Good idea. Want to submit a PR? :)

**Comment by jiwalker-usgs** [comment]
Yeah, I should be able to get to that soon.

**Comment by jread-usgs** [comment]
Can the version number be changed to reflect this addition? Looks like GH version is 1.0.0, which is the same as CRAN.

**Comment by gaborcsardi** [comment]
@jread-usgs Done in https://github.com/gaborcsardi/secret/commit/63145cf2ee0f396071d7e3abdc1d6e0ace4f029f
