### ISSUE TITLE
Secret on windows?

### ISSUE THREAD

**Issue by ignacio82** [gaborcsardi/secret#29]
I'm able to use secret on my Linux machine but not on windows. This is what I tried and the error I get:
```
> Sys.setenv(USER_KEY = normalizePath("/Users/IMartinez/.ssh/", mustWork = FALSE))
> Sys.getenv("USER_KEY")
[1] "C:\\Users\\IMartinez\\.ssh\\"
> dir(Sys.getenv("USER_KEY"))
[1] "id_rsa"      "id_rsa.pem"  "id_rsa.pub"  "known_hosts"
> local_key()
Error: !info$isdir is not TRUE
```

What am I doing wrong? Thanks!

**Comment by carpenn** [comment]
The local_key() function is a simple wrapper for the openssl package read_key() function. Hence a quick workaround is to call read_key() directly where-ever the secret package uses local_key(). Adding the following to your code should get you past the error..

`library(openssl)`  
`read_key("C:\\Users\\IMartinez\\.ssh\\id_rsa.pem")`

**Comment by gaborcsardi** [comment]
@ignacio82 `USER_KEY` must point to the actual key file, i.e. the `id_rsa` file in your case.
