### ISSUE TITLE
Tests relying on encrypted fail

### ISSUE THREAD

**Issue by jcpsantiago** [gaborcsardi/secret#33]
Tests that depend on encrypted data fail, because I can't decrypt the files. What is the recommended way of doing this?

My code (works outside the testing environment):
`library(secret)` in testthat.R
```
context("test-dostuff")

secret_data <- secret::get_secret("secret_data", vault = here::here("inst/vault"))

test_that("function is working", {
  expect_equal(my_fun(secret_data), "not_so_secret")
})
```

**Comment by gaborcsardi** [comment]
You'll have to put a public key in the package, and use it to retrieve the secret.
