### ISSUE TITLE
Is secret coming back to CRAN?

### ISSUE THREAD

**Issue by mfoos** [gaborcsardi/secret#37]
hi folks,

I'm really, really, really sorry to be that person who's like "AHEM you didn't fix this thing fast enough during a pandemic" but I have to make/justify a decision about using secret in an internal project. It looks like the removal from CRAN was an automated process generated by bad luck, etc. Can you just speak to whether the ultimate plan is to return to CRAN? (So I can assure others) thank you thank you. I understand you probably have other more important things going on!

**Comment by gaborcsardi** [comment]
Oh, I did not know that it was archived. Yeah, we'll put it back asap.

**Comment by mfoos** [comment]
thank you!

**Comment by mollonado** [comment]
@gaborcsardi do you know when the package will be put back to CRAN?

**Comment by sclewis23** [comment]
Are you just waiting on CRAN ?

**Comment by gaborcsardi** [comment]
No, I haven't submitted it yet, as there are some small things to fix. I'll submit it today, and hopefully it goes through quickly.

**Comment by gaborcsardi** [comment]
Back now, thanks for the patience. It turned out that the word "secret" is a red flag for spam filters, three emails were lost to/from CRAN....
