### ISSUE TITLE
GPG support?

### ISSUE THREAD

**Issue by egoipse** [gaborcsardi/secret#43]
Hi... This package is great. 

One feature would make it more powerful: **GPG support**.

As long as I tried, it seems to only work with PGP for asymmetric encryption. But GPG is incresing its marketshare. It would be great if we can use it with this package....

**Comment by gaborcsardi** [comment]
AFAIK PGP and GPG keys should be compatible. Can you please show what you tried that didn't work?

**Comment by egoipse** [comment]
Sure... I created a key-pair with gpg terminal commands. Then I tried to read the private key with `try(local_key(), silent = F)`, as stated in the Readme file. And I got an error message: `Error in read_key(path) : Failed to parse private key PEM file`.

It works fine with a PGP generated private key.
`

**Comment by gaborcsardi** [comment]
secret uses openssl to read in the key, and apparently it cannot read gpg keys. 

One option would be to use a tool to convert your gpg key to a pgp or openssl key. Unfortunately I am not sure about the current best option to do that.

**Comment by egoipse** [comment]
Ok. Thanks for the info. I'll explore which way is the better one to deal with this issue.
