### ISSUE TITLE
Add github PAT to Travis config to enable tests

### ISSUE THREAD

**Issue by andrie** [gaborcsardi/secret#9]
The tests for `add_github_user()` fails on Travis, because Travis makes anonymous requests to github. Since there is a rate limit on github for anonymous requests, the test sometimes pass and sometimes gets a 403 error.

The resolution to this is to add a github PAT to the Travis repo.

This is described at https://itsalocke.com/using-travis-make-sure-use-github-pat/

**Comment by andrie** [comment]
Ping.  This should take a few minutes and will help with getting the tests to run in Travis.

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by andrie** [comment]
I don't think that worked.  The keys need to be added to the Travis GUI, not the env vars in the config file.

**Comment by gaborcsardi** [comment]
I prefer the config file.

**Comment by andrie** [comment]
Great, I didn't think you could do this.
